config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # only: [:create, :index, :show, :update, :delete]
  resources :skills do
    resources :bookings, only: [:create, :new]
  end


  resources :bookings, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create , :destroy]
  end

  resources :bookings, only: [:destroy]
  get "profile", to: "dashboard#profile"
  patch "bookings/:id/accept", to: "bookings#accept"
  patch "bookings/:id/decline", to: "bookings#decline"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  has_one :review
  validates :status, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews , through: :bookings
  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, or_equal: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :skills
has_many :bookings
validates :name, presence: true
validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :check_logged_in
  before_action :set_booking, only: [:accept, :decline, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def new
    @skill = Skill.find(params[:skill_id])
    @booking = Booking.new
  end

  def create
    @skill = Skill.find(params[:skill_id])
    @booking = Booking.new(booking_params)
    @booking.skill = @skill
    @booking.user = current_user

    if @booking.save
      redirect_to profile_path, notice: "Booking successfully created"
    else
      flash[:alert] = "Booking could not be created. Please check your input."
      render :new
    end
  end



  def accept
    if @booking.update(status: "accepted")
      redirect_to profile_path, notice: "Booking accepted"
    else
      redirect_to profile_path, alert: "Unable to accept booking"
    end
  end

  def decline
    if @booking.update(status: "declined")
      redirect_to profile_path, notice: "Booking declined"
    else
      redirect_to profile_path, alert: "Unable to decline booking"
    end
  end

  def destroy
    if @booking.destroy
      redirect_to bookings_path, notice: "Booking deleted"
    else
      redirect_to bookings_path, alert: "Unable to delete booking"
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:message, :date)
  end

  def check_logged_in
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def profile
    @user = current_user
    @my_skills = Skill.where(user_id: @user.id)
    @my_bookings = Booking.where(user_id: @user.id)
    @my_requests = Booking.where(skill_id: @my_skills.pluck(:id))
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking

    if @review.save
      redirect_to skill_path(@booking.skill)
    end
  end
  def destroy

  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @search = params[:q]
    if @search
      @skills = Skill.where("LOWER(title) LIKE LOWER(?)",
          "%" + Skill.sanitize_sql_like(@search) + "%"
        )
    else
      @skills = Skill.all
    end
  end

  # def show
  #   check_logged_in
  #   @skill = Skill.find(params[:id])
  #   @bookings = current_user.bookings
  #   @booking = @bookings.find_by(skill_id: @skill.id)
  #   @review = Review.new
  # end
  #
  def show
    @skill = Skill.find(params[:id])
    @booking = Booking.new # Ensure @booking is initialized here
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to @skill, notice: 'Skill was successfully created.'
    else
      render :edit
    end
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)

    # Assuming users must be signed in to create skills
    @skill.user = current_user

    if @skill.save
      redirect_to @skill, notice: 'Skill was successfully created.'
    else
      render :new
    end
  end

  

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    redirect_to skills_path, notice: "Skill was deleted"
  end

  private

  def skill_params
    params.require(:skill).permit(:title, :description, :description_long, :price, :photo)
  end

  def check_logged_in
    if !current_user
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
  def categorize_skill(skill)
    case skill.title.downcase
    when /spanish|french|language/
      'Language'
    when /guitar|music|piano/
      'Music'
    when /archery|tennis|sports/
      'Sports'
    when /python|programming|tech/
      'Tech'
    when /yoga|wellness/
      'Wellness'
    when /creative|writing|art/
      'Art'
    when /cooking|culinary/
      'Culinary'
    when /business|finance/
      'Business'
    else
      'Other'
    end
  end
end

app/views/bookings/index.html.erb
<div class="container">
  <h1>My Bookings</h1>

  <div class="row">
    <% @bookings.each do |booking| %>
    <div class="col-12 col-md-6 col-lg-4 mb-4">
      <div class="card h-100">
        <!-- Skill Image -->
        <% if booking.skill.photo.attached? %>
          <%= cl_image_tag booking.skill.photo.key, class: "card-img-top" %>
        <% else %>
          <img src="https://via.placeholder.com/300x200" alt="No image available" class="card-img-top" />
        <% end %>
        <!-- Skill Information -->
        <div class="card-details">
          <h5 class="card-title"><%= link_to booking.skill.title, skill_path(booking.skill) %></h5>
          <div class="card-body">
            <p>Message: <%= booking.message %></p>
            <p>Date: <%= booking.date %></p>
            <p>Status: <%= booking.status %></p>
          </div>
        </div>
        <!-- Price in the Footer -->
        <div class="card-footer">
          <%= link_to "Delete Booking", booking_path(booking), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Start a new booking for <%= @skill.title %></h1>
  <%= simple_form_for [@skill, @booking] do |f| %>
    <%= f.input :message, placeholder: "Enter the booking message." %>
    <%= f.input :date, placeholder: "What day would you like to book?", type: "date" %>
    <%= f.submit "Add Booking" %>
  <% end %>
</div>

app/views/dashboard/profile.html.erb
<div class="container ml-4 mt-5" >
<h1 style="border-bottom: 1px solid #3B1C32; width: 70%; margin: 10px auto;">Hello <%= @user.name %></h1>

  <div class="row mt-4">
    <!-- First Column: My Skills -->
    <div class="col-md-4">
      <div class="p-4  rounded-lg mt-4  " style="border-radius: 20px;">
      <h2>My Skills</h2>
      <% @my_skills.each do |skill| %>
        <div class=" card-2 border rounded-lg mb-4 mt-4" id="skills">
          <!-- Skill Image -->
          <% if skill.photo.attached? %>
            <%= cl_image_tag skill.photo.key, class: "card-img-top" %>
          <% else %>
            <img src="https://via.placeholder.com/300x200" alt="No image available" class="card-img-top" />
          <% end %>
          <!-- Skill Information -->
          <div class="card-details p-3">
            <h5 class="card-title"><%= link_to skill.title, skill_path(skill) %></h5>
            <p class="card-text">Description: <%= skill.description %></p>
             <div class="card-footer">
            <%= link_to "Edit", "#", class: "btn btn-danger"%>
             </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>

    <!-- Second Column: Requests -->
    <div class="col-md-4">
      <div class="p-4  rounded-lg mt-4  " style="border-radius: 20px;">
      <h2>Requests:  <%= @my_requests.count %></h2>
      <% @my_requests.each do |request| %>
        <div class="card-2 border rounded-lg mb-4 mt-4">
          <!-- Request Image -->
          <% if request.skill.photo.attached? %>
            <%= cl_image_tag request.skill.photo.key, class: "card-img-top" %>
          <% else %>
            <img src="https://via.placeholder.com/300x200" alt="No image available" class="card-img-top" />
          <% end %>
          <!-- Request Information -->
          <div class="card-details p-3">
            <h5 class="card-title"><%= link_to request.skill.title, skill_path(request.skill) %></h5>
            <p class="card-text">Message: <%= request.message %></p>
            <p class="card-text">Date: <%= request.date %></p>
            <p class="card-text">Status: <strong><%= request.status %></strong></p>
          </div>
          <div class="p-4 card-footer">
            <%= link_to "Accept", "bookings/#{request.id}/accept", class: "btn btn-success", data: { turbo_method: :patch } %>
            <%= link_to "Reject", "bookings/#{request.id}/decline", class: "btn btn-danger", data: { turbo_method: :patch } %>
          </div>
        </div>
      <% end %>
    </div>
    </div>

    <!-- Third Column: My Bookings -->
    <div class="col-md-4">
      <div class="p-4  rounded-lg mt-4  " style="border-radius: 20px;">
      <h2>My Bookings:  <%= @my_bookings.count %></h2>
      <% @my_bookings.each do |booking| %>
        <div class="card-2 border rounded-lg mb-4 mt-4" id="completed">
          <!-- Booking Image -->
          <% if booking.skill.photo.attached? %>
            <%= cl_image_tag booking.skill.photo.key, class: "card-img-top" %>
          <% else %>
            <img src="https://via.placeholder.com/300x200" alt="No image available" class="card-img-top" />
          <% end %>
          <!-- Booking Information -->
          <div class="card-details p-3">
            <h5 class="card-title"><%= link_to booking.skill.title, skill_path(booking.skill) %></h5>
            <p class="card-text">Message: <%= booking.message %></p>
            <p class="card-text">Date: <%= booking.date %></p>
            <p class="card-text">Status: <strong> <%= booking.status %></strong></p>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skills4hire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  <% flash.each do |type, msg| %>
    <div>
      <% if type == "notice" %>
        <div class="alert alert-success" role="alert">
          <%= msg %>
        </div>
      <% elsif type == "alert" %>
        <div class="alert alert-danger" role="alert">
          <%= msg %>
        </div>
      <% else %>
        <div class="alert alert-primary" role="alert">
          <%= msg %>
        </div>
      <% end %>
    </div>
  <% end %>
  </body>


<footer class="page-footer mt-4">
  <div class="footer-container">
    <div class="footer-section">
      <h5>About</h5>
      <ul>
        <li><a href="#">Company Info</a></li>
        <li><a href="#">Our Team</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Press</a></li>
      </ul>
    </div>
    <div class="footer-section">
      <h5>Help</h5>
      <ul>
        <li><a href="#">Support Center</a></li>
        <li><a href="#">FAQs</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">Feedback</a></li>
      </ul>
    </div>
    <div class="footer-section">
      <h5>Legal</h5>
      <ul>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Cookie Policy</a></li>
      </ul>
    </div>
    <div class="footer-section social-media">
      <h5>Follow Us</h5>
      <div class="social-icons">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <p>&copy; 2024 Skills4Hire. All rights reserved.</p>
    <p><a href="#">Site Map</a></p>
  </div>
</footer>


</html>

app/views/pages/home.html.erb
<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Skills4Hire</h1>
<%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>
    <%# <p>Share your passion</p>
    <a class="btn btn-flat" href="#">Discover</a>
  </div>
</div> %>


<div style="position: relative; height: calc(100vh - 66px); background: #000000">
  <video autoplay loop muted style="position: absolute; width: 100%; height: 100%; object-fit: cover; opacity: 0.6">
    <source src="https://res.cloudinary.com/do1nrl43q/video/upload/v1728474291/homepage_z9lzse.mp4" type="video/mp4">
    <%# Your browser does not support the video tag. %>
    homepage_z9lzse
  </video>
  <div style="position: relative; z-index: 1; color: #d1d1d1; text-align: center; padding-top: 520px;">

    <h3>Share your passion</h3>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="https://res.cloudinary.com/do1nrl43q/image/upload/v1728635948/skills4hirelogo_xsrogs.jpg" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item active" id="search">
          <div class="nav-link">
            <form method="get" action="<%= skills_path %>" class="d-flex align-items-center">
              <!-- Search Input Field -->
              <input name="q" value="<%= @search %>" placeholder="Search " class="form-control me-2">

              <!-- Submit Button with Image Icon -->
              <button type="submit" class="btn  p-0">
                <i class="fa-solid fa-magnifying-glass"></i>
              </button>
            </form>
          </div>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="<%= skills_path %>">All Skills</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="<%= new_skill_path %>">Share your passion</a>
        </li>
</ul>

 <ul class="navbar-nav me-auto">

        <li class="nav-item dropdown">
          <% if user_signed_in? %>
            <%= image_tag("https://avatars.githubusercontent.com/u/158226356?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }) %>
          <% else %>
            <%= image_tag("https://www.shutterstock.com/image-vector/default-avatar-profile-icon-vector-600nw-1745180411.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }) %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to("Dashboard", profile_path, class: "dropdown-item") %>
              <%= link_to("Log Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "dropdown-item") %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            <% end %>
            <%# <a class="dropdown-item" data-turbo-method="delete" href="">Log out</a> %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/skills/edit.html.erb
<div class="container">
  <h1>Edit a skill</h1>
  <%= simple_form_for(@skill) do |f| %>
    <%= f.input :title, placeholder: "Enter your skill title" %>
    <%= f.input :description, placeholder: "Enter your skill description" %>
    <%= f.input :description_long, placeholder: "Enter your long skill description", :as => :text, :input_html => { 'rows' => 5, 'cols' => 10 } %>
    <%= f.input :price, placeholder: "Enter your price in pounds" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Edit Skill" %>
  <% end %>
</div>

app/views/skills/index.html.erb
<div class="show-page mb-5">


<div class="carousel mx-auto" style="width: 60%;">

  <div class="carousel__container">
    <% @skills.reverse.each do |skill| %>
      <div class="card" id="carousel-item">
        <%= link_to skill_path(skill) do %>
          <%= cl_image_tag skill.photo.key, class: "card-img-top carousel-item__img" %>
        <% end %>
        <div class="carousel-item__details">
          <h5 class="carousel-item__details--title"><strong> <%= categorize_skill(skill) %></strong></h5>
            <%# <%= skill.title.split.first %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="mx-auto" style="width: 70%;">

<div class="container mt-4 mb-5 ">
  <h1><strong>Discover your next passion </strong></h1>
</div>






  <!-- Main Row Wrapper for the Cards -->
<div class="container mt-4">
  <div class="row justify-content-left mx-auto m-2">
    <% @skills.each do |skill| %>
      <!-- Each Skill Card Column (3 columns per row on large screens) -->
    <div class="col-12 col-md-6 col-lg-4 mb-3 d-flex justify-content-left">

        <div class="card h-100">
          <!-- Skill Image -->
          <% if skill.photo.attached? %>
            <%= cl_image_tag skill.photo.key, class: "card-img-top" %>
          <% else %>
            <img src="https://via.placeholder.com/300x200" alt="No image available" class="card-img-top" />
          <% end %>

        <div class="card-content">

          <!-- Skill Information -->
          <div class="card-details">
            <h5 class="card-title mt-5"><%= link_to skill.title, skill_path(skill) %></h5>
            <p class="card-body"><%= skill.description %></p>
          </div>

          <!-- Price in the Footer -->
          <div  class="footer">

          <%= link_to "More details", skill_path(skill), class: "btn btn-primary" %>

            <small>Price: <%= number_to_currency(skill.price, unit: "£") %></small>
          </div>

        </div>
      </div>
  </div>
    <% end %>
        </div>
</div>
</div>


 <div class="background"></div>
    <div class="background-texture"></div>
</div>

app/views/skills/new.html.erb
<div class="form-page mt-4">
      <div class="container mt-5" id="form-new">
        <h1>Share your passion</h1>
        <%= simple_form_for(@skill) do |f| %>
          <%= f.input :title, placeholder: "Enter your skill title" %>
          <%= f.input :description, placeholder: "Enter your skill description" %>
    <%= f.input :description_long, placeholder: "Enter your long skill description", :as => :text, :input_html => { 'rows' => 5, 'cols' => 10 } %>
          <%= f.input :price, placeholder: "Enter your price in pounds" %>
            <%= f.input :photo, as: :file %>
          <%= f.submit "Add Skill", class:"btn btn-primary mt-4" %>
        <% end %>
      </div>
</div>

app/views/skills/show.html.erb
<div class="container mb-4 p-4  mt-3" id="show-card" style="border-radius: 20px; width: 60%;" id="show-page">

  <div class="container-fluid mt-2" >
    <div class="row"  style=" display: flex; justify-content: space-between; ">
      <!-- Skill Image and Title -->
      <div class="col-12 mb-4">
        <% if @skill.photo.attached? %>
          <div class="cover-image" style="background-image: url('<%= cl_image_path(@skill.photo.key, height: 500, crop: :fill) %>'); border-radius: 20px;">
            <div class="overlay"></div>
          </div>
        <% end %>
        <h1 class="mt-3"><%= @skill.title %></h1>
      </div>



      <!-- Description and Details Section -->
      <div class="col-md-6">
          <h3>Description</h3>
        <div class="p-3 text-start p-4 border rounded-lg mt-4 shadow " style="border-radius: 20px; ">
          <p><%= @skill.description %></p>
          <p class="skill-description mt-3"><%= @skill.description_long %></p>
        </div>

          <div class="p-4 border  rounded-lg mt-4 " style="border-radius: 20px; background-color: #C7C8CC; ">
          <p>Offered by: <strong> <%= @skill.user.name %> </strong> </p>
          <p><%= @skill.user.about %></p>
      </div>
         </div>

      <!-- Booking Form Section -->
      <div class="col-md-5"  >
          <h3>Make a New Booking</h3>
       <div class="p-4 border rounded-lg mt-4 shadow " style="border-radius: 20px; ">
           <%# <%= link_to 'Make a booking', new_skill_booking_path(@skill), class: "btn btn-primary" %>

                  <% if @booking %>
              <div class="container" >
                <h4>Start a new booking for <%= @skill.title %></h4>
                <%= simple_form_for [@skill, @booking] do |f| %>
                  <%= f.input :message, placeholder: "Enter the booking message." %>
                  <%= f.input :date, placeholder: "What day would you like to book?", type: "date" %>
                  <%= f.submit "Add Booking", class: "btn btn-secondary mt-2" %>
                <% end %>
              </div>
            <% else %>
              <p>Booking information is not available.</p>
            <% end %>

        </div>

     <h3 class="mt-5">Reviews</h3>
<div class="p-4 mt-2 ">
<% @skill.reviews.each do |review| %>
  <div class="container mt-4 text-left p-4 border rounded-lg mt-4 shadow" style="border-radius: 20px;">

    <p><strong> <%= review.booking.user.name %>:</strong> <%= review.comment %></p>
    <p><strong>Rating:</strong>
      <% review.rating.to_i.times do %>
        <i class="fa fa-star text-warning"></i> <!-- Font Awesome filled star icon -->
      <% end %>
    </p>
  </div>
<% end %>




      <!-- Price Section -->
          <h3 class=" mt-4 text-center">Price</h3>

        <div class="container mt-4 text-left p-4 border rounded-lg mt-4 " style="border-radius: 20px; background-color: #C7C8CC;">
          <p>Price: <%= number_to_currency(@skill.price, unit: "£") %></p>
        </div>
      </div>

  </div>
</div>

  <!-- Back Button -->
  <div class="mt-4 text-center mb-4">
    <%= link_to 'Back to Skills', skills_path, class: "btn btn-secondary" %>
  </div>
</div>
</div>